// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'GeneralVo.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

GeneralVo _$GeneralVoFromJson(Map<String, dynamic> json) {
  return GeneralVo(
    json['id'] as int,
    json['arcCode'] as String,
    json['arcName'] as String,
    json['isSelect'] as bool,
    json['testRule'] as String,
    json['docCat'] as String,
    json['beginDate'] as String,
    json['endDate'] as String,
    json['docNo'] as String,
    json['invCode'] as String,
    json['invName'] as String,
    json['auditStatus'] as String,
    json['checkerId'] as String,
    json['checkerName'] as String,
    json['testCat'] as String,
    json['invCatCode'] as String,
    json['invCatName'] as String,
    json['opCode'] as String,
    json['opName'] as String,
    json['srcDocDetailId'] as String,
    json['testTemplateId'] as String,
    json['qty'] as String,
    json['pageIndex'] as int,
    json['pageSize'] as int,
    json['checkStatus'] as String,
    json['arrivalDocNo'] as String,
    json['moDocNo'] as String,
    json['srcDocNo'] as String,
    json['cusCode'] as String,
    json['cusName'] as String,
    json['batchNumber'] as String,
    json['socode'] as String,
    json['protype'] as String,
    json['opDocNo'] as String,
    json['wcCode'] as String,
    json['wcName'] as String,
    json['supplierCode'] as String,
    json['supplierName'] as String,
  );
}

Map<String, dynamic> _$GeneralVoToJson(GeneralVo instance) => <String, dynamic>{
      'id': instance.id,
      'arcCode': instance.arcCode,
      'arcName': instance.arcName,
      'isSelect': instance.isSelect,
      'testRule': instance.testRule,
      'docCat': instance.docCat,
      'beginDate': instance.beginDate,
      'endDate': instance.endDate,
      'docNo': instance.docNo,
      'invCode': instance.invCode,
      'invName': instance.invName,
      'auditStatus': instance.auditStatus,
      'checkerId': instance.checkerId,
      'checkerName': instance.checkerName,
      'testCat': instance.testCat,
      'invCatCode': instance.invCatCode,
      'invCatName': instance.invCatName,
      'opCode': instance.opCode,
      'opName': instance.opName,
      'srcDocDetailId': instance.srcDocDetailId,
      'testTemplateId': instance.testTemplateId,
      'qty': instance.qty,
      'pageIndex': instance.pageIndex,
      'pageSize': instance.pageSize,
      'checkStatus': instance.checkStatus,
      'arrivalDocNo': instance.arrivalDocNo,
      'moDocNo': instance.moDocNo,
      'srcDocNo': instance.srcDocNo,
      'cusCode': instance.cusCode,
      'cusName': instance.cusName,
      'batchNumber': instance.batchNumber,
      'socode': instance.socode,
      'protype': instance.protype,
      'opDocNo': instance.opDocNo,
      'wcCode': instance.wcCode,
      'wcName': instance.wcName,
      'supplierCode': instance.supplierCode,
      'supplierName': instance.supplierName,
    };
